plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.sample_test'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId "com.example.sample_test"
        minSdk 29
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug{
            testCoverageEnabled true

            // Enable coverage for unit tests
            //enableUnitTestCoverage true
            // Enable coverage for instrumentation tests
            //enableAndroidTestCoverage true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    testImplementation libs.junit
    testImplementation libs.junit.jupiter
    testImplementation libs.junit.jupiter
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
    androidTestImplementation "com.android.support.test.espresso:espresso-core:3.0.2"
}